2023-09-10 15:39:30,274:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 15:39:30,274:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 15:39:30,274:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 15:39:30,274:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-10 16:06:14,153:INFO:PyCaret ClassificationExperiment
2023-09-10 16:06:14,153:INFO:Logging name: clf-default-name
2023-09-10 16:06:14,153:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-09-10 16:06:14,153:INFO:version 3.0.4
2023-09-10 16:06:14,153:INFO:Initializing setup()
2023-09-10 16:06:14,153:INFO:self.USI: 01d6
2023-09-10 16:06:14,153:INFO:self._variable_keys: {'pipeline', '_ml_usecase', 'y_test', 'memory', 'seed', 'gpu_param', 'data', 'fold_groups_param', 'log_plots_param', 'target_param', 'exp_id', 'logging_param', 'USI', 'X_test', 'X', 'exp_name_log', 'n_jobs_param', 'fold_generator', 'y_train', 'idx', 'fold_shuffle_param', '_available_plots', 'gpu_n_jobs_param', 'y', 'X_train', 'html_param', 'is_multiclass', 'fix_imbalance'}
2023-09-10 16:06:14,153:INFO:Checking environment
2023-09-10 16:06:14,153:INFO:python_version: 3.9.17
2023-09-10 16:06:14,153:INFO:python_build: ('main', 'Jul  5 2023 20:47:11')
2023-09-10 16:06:14,153:INFO:machine: AMD64
2023-09-10 16:06:14,153:INFO:platform: Windows-10-10.0.22621-SP0
2023-09-10 16:06:14,168:INFO:Memory: svmem(total=8384401408, available=952975360, percent=88.6, used=7431426048, free=952975360)
2023-09-10 16:06:14,168:INFO:Physical Core: 4
2023-09-10 16:06:14,169:INFO:Logical Core: 8
2023-09-10 16:06:14,169:INFO:Checking libraries
2023-09-10 16:06:14,169:INFO:System:
2023-09-10 16:06:14,169:INFO:    python: 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)]
2023-09-10 16:06:14,169:INFO:executable: c:\Users\LP00035\anaconda3\envs\mlflow\python.exe
2023-09-10 16:06:14,169:INFO:   machine: Windows-10-10.0.22621-SP0
2023-09-10 16:06:14,169:INFO:PyCaret required dependencies:
2023-09-10 16:06:14,186:INFO:                 pip: 23.2.1
2023-09-10 16:06:14,186:INFO:          setuptools: 68.0.0
2023-09-10 16:06:14,186:INFO:             pycaret: 3.0.4
2023-09-10 16:06:14,186:INFO:             IPython: 8.15.0
2023-09-10 16:06:14,186:INFO:          ipywidgets: 7.8.0
2023-09-10 16:06:14,186:INFO:                tqdm: 4.66.1
2023-09-10 16:06:14,186:INFO:               numpy: 1.23.5
2023-09-10 16:06:14,186:INFO:              pandas: 1.5.3
2023-09-10 16:06:14,186:INFO:              jinja2: 3.1.2
2023-09-10 16:06:14,186:INFO:               scipy: 1.11.2
2023-09-10 16:06:14,186:INFO:              joblib: 1.3.2
2023-09-10 16:06:14,186:INFO:             sklearn: 1.2.2
2023-09-10 16:06:14,186:INFO:                pyod: 1.1.0
2023-09-10 16:06:14,186:INFO:            imblearn: 0.11.0
2023-09-10 16:06:14,186:INFO:   category_encoders: 2.6.2
2023-09-10 16:06:14,186:INFO:            lightgbm: 4.0.0
2023-09-10 16:06:14,186:INFO:               numba: 0.57.1
2023-09-10 16:06:14,186:INFO:            requests: 2.31.0
2023-09-10 16:06:14,186:INFO:          matplotlib: 3.7.2
2023-09-10 16:06:14,186:INFO:          scikitplot: 0.3.7
2023-09-10 16:06:14,186:INFO:         yellowbrick: 1.5
2023-09-10 16:06:14,186:INFO:              plotly: 5.16.1
2023-09-10 16:06:14,186:INFO:    plotly-resampler: Not installed
2023-09-10 16:06:14,186:INFO:             kaleido: 0.2.1
2023-09-10 16:06:14,186:INFO:           schemdraw: 0.15
2023-09-10 16:06:14,200:INFO:         statsmodels: 0.14.0
2023-09-10 16:06:14,200:INFO:              sktime: 0.22.0
2023-09-10 16:06:14,200:INFO:               tbats: 1.1.3
2023-09-10 16:06:14,200:INFO:            pmdarima: 2.0.3
2023-09-10 16:06:14,200:INFO:              psutil: 5.9.5
2023-09-10 16:06:14,200:INFO:          markupsafe: 2.1.3
2023-09-10 16:06:14,200:INFO:             pickle5: Not installed
2023-09-10 16:06:14,200:INFO:         cloudpickle: 2.2.1
2023-09-10 16:06:14,200:INFO:         deprecation: 2.1.0
2023-09-10 16:06:14,200:INFO:              xxhash: 3.3.0
2023-09-10 16:06:14,200:INFO:           wurlitzer: Not installed
2023-09-10 16:06:14,200:INFO:PyCaret optional dependencies:
2023-09-10 16:06:14,392:INFO:                shap: Not installed
2023-09-10 16:06:14,392:INFO:           interpret: Not installed
2023-09-10 16:06:14,392:INFO:                umap: Not installed
2023-09-10 16:06:14,392:INFO:    pandas_profiling: 4.5.1
2023-09-10 16:06:14,392:INFO:  explainerdashboard: Not installed
2023-09-10 16:06:14,392:INFO:             autoviz: Not installed
2023-09-10 16:06:14,392:INFO:           fairlearn: Not installed
2023-09-10 16:06:14,392:INFO:          deepchecks: Not installed
2023-09-10 16:06:14,392:INFO:             xgboost: Not installed
2023-09-10 16:06:14,392:INFO:            catboost: Not installed
2023-09-10 16:06:14,392:INFO:              kmodes: Not installed
2023-09-10 16:06:14,392:INFO:             mlxtend: Not installed
2023-09-10 16:06:14,392:INFO:       statsforecast: Not installed
2023-09-10 16:06:14,392:INFO:        tune_sklearn: Not installed
2023-09-10 16:06:14,392:INFO:                 ray: Not installed
2023-09-10 16:06:14,392:INFO:            hyperopt: Not installed
2023-09-10 16:06:14,392:INFO:              optuna: Not installed
2023-09-10 16:06:14,392:INFO:               skopt: Not installed
2023-09-10 16:06:14,392:INFO:              mlflow: 2.6.0
2023-09-10 16:06:14,393:INFO:              gradio: Not installed
2023-09-10 16:06:14,393:INFO:             fastapi: 0.103.1
2023-09-10 16:06:14,393:INFO:             uvicorn: 0.23.2
2023-09-10 16:06:14,393:INFO:              m2cgen: Not installed
2023-09-10 16:06:14,393:INFO:           evidently: Not installed
2023-09-10 16:06:14,393:INFO:               fugue: Not installed
2023-09-10 16:06:14,393:INFO:           streamlit: 1.26.0
2023-09-10 16:06:14,393:INFO:             prophet: Not installed
2023-09-10 16:06:14,393:INFO:None
2023-09-10 16:06:14,393:INFO:Set up data.
2023-09-10 16:06:14,485:INFO:Set up train/test split.
2023-09-10 16:06:14,554:INFO:Set up index.
2023-09-10 16:06:14,554:INFO:Set up folding strategy.
2023-09-10 16:06:14,554:INFO:Assigning column types.
2023-09-10 16:06:14,568:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-09-10 16:06:14,622:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,624:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,661:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,661:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,705:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,705:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,737:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,737:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,737:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-09-10 16:06:14,787:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,822:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,822:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,872:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-10 16:06:14,902:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,902:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:14,902:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-09-10 16:06:15,025:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:15,026:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:15,104:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:15,104:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:15,104:INFO:Preparing preprocessing pipeline...
2023-09-10 16:06:15,117:INFO:Set up simple imputation.
2023-09-10 16:06:15,136:INFO:Set up encoding of ordinal features.
2023-09-10 16:06:15,153:INFO:Set up encoding of categorical features.
2023-09-10 16:06:15,153:INFO:Set up column name cleaning.
2023-09-10 16:06:16,352:INFO:Finished creating preprocessing pipeline.
2023-09-10 16:06:16,418:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\LP00035\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['loan_amount', 'term', 'dtir1'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_...
                                    include=['Gender', 'credit_type'],
                                    transformer=OneHotEncoder(cols=['Gender',
                                                                    'credit_type'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-09-10 16:06:16,418:INFO:Creating final display dataframe.
2023-09-10 16:06:17,383:INFO:Setup _display_container:                     Description             Value
0                    Session id              3846
1                        Target            Status
2                   Target type            Binary
3           Original data shape      (148670, 11)
4        Transformed data shape      (148670, 17)
5   Transformed train set shape      (104069, 17)
6    Transformed test set shape       (44601, 17)
7              Ordinal features                 5
8              Numeric features                 3
9          Categorical features                 7
10     Rows with missing values             16.3%
11                   Preprocess              True
12              Imputation type            simple
13           Numeric imputation              mean
14       Categorical imputation              mode
15     Maximum one-hot encoding                25
16              Encoding method              None
17               Fold Generator   StratifiedKFold
18                  Fold Number                10
19                     CPU Jobs                -1
20                      Use GPU             False
21               Log Experiment             False
22              Experiment Name  clf-default-name
23                          USI              01d6
2023-09-10 16:06:17,497:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:17,497:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:17,570:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:17,570:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-10 16:06:17,581:INFO:setup() successfully completed in 4.76s...............
2023-09-10 16:07:16,164:INFO:Initializing compare_models()
2023-09-10 16:07:16,164:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-10 16:07:16,164:INFO:Checking exceptions
2023-09-10 16:07:16,196:INFO:Preparing display monitor
2023-09-10 16:07:16,250:INFO:Initializing Logistic Regression
2023-09-10 16:07:16,250:INFO:Total runtime is 0.0 minutes
2023-09-10 16:07:16,257:INFO:SubProcess create_model() called ==================================
2023-09-10 16:07:16,258:INFO:Initializing create_model()
2023-09-10 16:07:16,259:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:07:16,259:INFO:Checking exceptions
2023-09-10 16:07:16,260:INFO:Importing libraries
2023-09-10 16:07:16,260:INFO:Copying training dataset
2023-09-10 16:07:16,351:INFO:Defining folds
2023-09-10 16:07:16,351:INFO:Declaring metric variables
2023-09-10 16:07:16,358:INFO:Importing untrained model
2023-09-10 16:07:16,367:INFO:Logistic Regression Imported successfully
2023-09-10 16:07:16,381:INFO:Starting cross validation
2023-09-10 16:07:16,384:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:07:25,387:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,399:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,499:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,599:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,649:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,683:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,716:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:25,885:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:28,898:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:28,914:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:07:31,275:INFO:Calculating mean and std
2023-09-10 16:07:31,282:INFO:Creating metrics dataframe
2023-09-10 16:07:31,930:INFO:Uploading results into container
2023-09-10 16:07:31,930:INFO:Uploading model into container now
2023-09-10 16:07:31,930:INFO:_master_model_container: 1
2023-09-10 16:07:31,930:INFO:_display_container: 2
2023-09-10 16:07:31,930:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=3846, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-10 16:07:31,930:INFO:create_model() successfully completed......................................
2023-09-10 16:07:32,150:INFO:SubProcess create_model() end ==================================
2023-09-10 16:07:32,150:INFO:Creating metrics dataframe
2023-09-10 16:07:32,164:INFO:Initializing K Neighbors Classifier
2023-09-10 16:07:32,164:INFO:Total runtime is 0.26524166266123456 minutes
2023-09-10 16:07:32,169:INFO:SubProcess create_model() called ==================================
2023-09-10 16:07:32,169:INFO:Initializing create_model()
2023-09-10 16:07:32,169:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:07:32,169:INFO:Checking exceptions
2023-09-10 16:07:32,169:INFO:Importing libraries
2023-09-10 16:07:32,169:INFO:Copying training dataset
2023-09-10 16:07:32,211:INFO:Defining folds
2023-09-10 16:07:32,211:INFO:Declaring metric variables
2023-09-10 16:07:32,215:INFO:Importing untrained model
2023-09-10 16:07:32,219:INFO:K Neighbors Classifier Imported successfully
2023-09-10 16:07:32,228:INFO:Starting cross validation
2023-09-10 16:07:32,230:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:08:27,239:INFO:Calculating mean and std
2023-09-10 16:08:27,240:INFO:Creating metrics dataframe
2023-09-10 16:08:28,005:INFO:Uploading results into container
2023-09-10 16:08:28,005:INFO:Uploading model into container now
2023-09-10 16:08:28,018:INFO:_master_model_container: 2
2023-09-10 16:08:28,018:INFO:_display_container: 2
2023-09-10 16:08:28,018:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-10 16:08:28,018:INFO:create_model() successfully completed......................................
2023-09-10 16:08:28,226:INFO:SubProcess create_model() end ==================================
2023-09-10 16:08:28,226:INFO:Creating metrics dataframe
2023-09-10 16:08:28,244:INFO:Initializing Naive Bayes
2023-09-10 16:08:28,244:INFO:Total runtime is 1.199903678894043 minutes
2023-09-10 16:08:28,250:INFO:SubProcess create_model() called ==================================
2023-09-10 16:08:28,250:INFO:Initializing create_model()
2023-09-10 16:08:28,250:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:08:28,250:INFO:Checking exceptions
2023-09-10 16:08:28,250:INFO:Importing libraries
2023-09-10 16:08:28,250:INFO:Copying training dataset
2023-09-10 16:08:28,289:INFO:Defining folds
2023-09-10 16:08:28,289:INFO:Declaring metric variables
2023-09-10 16:08:28,293:INFO:Importing untrained model
2023-09-10 16:08:28,301:INFO:Naive Bayes Imported successfully
2023-09-10 16:08:28,314:INFO:Starting cross validation
2023-09-10 16:08:28,314:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:08:37,145:INFO:Calculating mean and std
2023-09-10 16:08:37,147:INFO:Creating metrics dataframe
2023-09-10 16:08:37,818:INFO:Uploading results into container
2023-09-10 16:08:37,818:INFO:Uploading model into container now
2023-09-10 16:08:37,827:INFO:_master_model_container: 3
2023-09-10 16:08:37,827:INFO:_display_container: 2
2023-09-10 16:08:37,827:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-10 16:08:37,827:INFO:create_model() successfully completed......................................
2023-09-10 16:08:38,033:INFO:SubProcess create_model() end ==================================
2023-09-10 16:08:38,033:INFO:Creating metrics dataframe
2023-09-10 16:08:38,048:INFO:Initializing Decision Tree Classifier
2023-09-10 16:08:38,048:INFO:Total runtime is 1.3632993817329406 minutes
2023-09-10 16:08:38,048:INFO:SubProcess create_model() called ==================================
2023-09-10 16:08:38,048:INFO:Initializing create_model()
2023-09-10 16:08:38,048:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:08:38,048:INFO:Checking exceptions
2023-09-10 16:08:38,048:INFO:Importing libraries
2023-09-10 16:08:38,048:INFO:Copying training dataset
2023-09-10 16:08:38,102:INFO:Defining folds
2023-09-10 16:08:38,102:INFO:Declaring metric variables
2023-09-10 16:08:38,107:INFO:Importing untrained model
2023-09-10 16:08:38,111:INFO:Decision Tree Classifier Imported successfully
2023-09-10 16:08:38,115:INFO:Starting cross validation
2023-09-10 16:08:38,115:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:08:47,401:INFO:Calculating mean and std
2023-09-10 16:08:47,402:INFO:Creating metrics dataframe
2023-09-10 16:08:48,066:INFO:Uploading results into container
2023-09-10 16:08:48,067:INFO:Uploading model into container now
2023-09-10 16:08:48,068:INFO:_master_model_container: 4
2023-09-10 16:08:48,068:INFO:_display_container: 2
2023-09-10 16:08:48,069:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=3846, splitter='best')
2023-09-10 16:08:48,069:INFO:create_model() successfully completed......................................
2023-09-10 16:08:48,275:INFO:SubProcess create_model() end ==================================
2023-09-10 16:08:48,275:INFO:Creating metrics dataframe
2023-09-10 16:08:48,293:INFO:Initializing SVM - Linear Kernel
2023-09-10 16:08:48,294:INFO:Total runtime is 1.534076964855194 minutes
2023-09-10 16:08:48,300:INFO:SubProcess create_model() called ==================================
2023-09-10 16:08:48,300:INFO:Initializing create_model()
2023-09-10 16:08:48,300:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:08:48,300:INFO:Checking exceptions
2023-09-10 16:08:48,300:INFO:Importing libraries
2023-09-10 16:08:48,300:INFO:Copying training dataset
2023-09-10 16:08:48,341:INFO:Defining folds
2023-09-10 16:08:48,342:INFO:Declaring metric variables
2023-09-10 16:08:48,348:INFO:Importing untrained model
2023-09-10 16:08:48,354:INFO:SVM - Linear Kernel Imported successfully
2023-09-10 16:08:48,357:INFO:Starting cross validation
2023-09-10 16:08:48,364:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:08:59,724:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:00,543:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:00,878:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:01,172:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:01,422:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:01,905:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:03,406:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:04,155:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:08,591:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:08,699:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-10 16:09:08,717:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:09:09,262:INFO:Calculating mean and std
2023-09-10 16:09:09,264:INFO:Creating metrics dataframe
2023-09-10 16:09:10,054:INFO:Uploading results into container
2023-09-10 16:09:10,054:INFO:Uploading model into container now
2023-09-10 16:09:10,054:INFO:_master_model_container: 5
2023-09-10 16:09:10,054:INFO:_display_container: 2
2023-09-10 16:09:10,054:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=3846, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-10 16:09:10,054:INFO:create_model() successfully completed......................................
2023-09-10 16:09:10,273:INFO:SubProcess create_model() end ==================================
2023-09-10 16:09:10,273:INFO:Creating metrics dataframe
2023-09-10 16:09:10,290:INFO:Initializing Ridge Classifier
2023-09-10 16:09:10,290:INFO:Total runtime is 1.9006632208824157 minutes
2023-09-10 16:09:10,296:INFO:SubProcess create_model() called ==================================
2023-09-10 16:09:10,297:INFO:Initializing create_model()
2023-09-10 16:09:10,297:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:09:10,297:INFO:Checking exceptions
2023-09-10 16:09:10,298:INFO:Importing libraries
2023-09-10 16:09:10,298:INFO:Copying training dataset
2023-09-10 16:09:10,334:INFO:Defining folds
2023-09-10 16:09:10,334:INFO:Declaring metric variables
2023-09-10 16:09:10,340:INFO:Importing untrained model
2023-09-10 16:09:10,348:INFO:Ridge Classifier Imported successfully
2023-09-10 16:09:10,357:INFO:Starting cross validation
2023-09-10 16:09:10,359:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:09:11,961:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,040:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,041:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,116:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,145:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,166:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,196:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:12,315:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:14,560:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:14,560:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-10 16:09:18,521:INFO:Calculating mean and std
2023-09-10 16:09:18,523:INFO:Creating metrics dataframe
2023-09-10 16:09:19,204:INFO:Uploading results into container
2023-09-10 16:09:19,204:INFO:Uploading model into container now
2023-09-10 16:09:19,208:INFO:_master_model_container: 6
2023-09-10 16:09:19,208:INFO:_display_container: 2
2023-09-10 16:09:19,208:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=3846, solver='auto',
                tol=0.0001)
2023-09-10 16:09:19,208:INFO:create_model() successfully completed......................................
2023-09-10 16:09:19,412:INFO:SubProcess create_model() end ==================================
2023-09-10 16:09:19,413:INFO:Creating metrics dataframe
2023-09-10 16:09:19,429:INFO:Initializing Random Forest Classifier
2023-09-10 16:09:19,429:INFO:Total runtime is 2.052988342444102 minutes
2023-09-10 16:09:19,432:INFO:SubProcess create_model() called ==================================
2023-09-10 16:09:19,432:INFO:Initializing create_model()
2023-09-10 16:09:19,432:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:09:19,432:INFO:Checking exceptions
2023-09-10 16:09:19,432:INFO:Importing libraries
2023-09-10 16:09:19,432:INFO:Copying training dataset
2023-09-10 16:09:19,474:INFO:Defining folds
2023-09-10 16:09:19,474:INFO:Declaring metric variables
2023-09-10 16:09:19,478:INFO:Importing untrained model
2023-09-10 16:09:19,484:INFO:Random Forest Classifier Imported successfully
2023-09-10 16:09:19,492:INFO:Starting cross validation
2023-09-10 16:09:19,499:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:09:55,269:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.61s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:55,582:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.52s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:55,895:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.64s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:56,535:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.63s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:56,925:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.79s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:57,541:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.74s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:09:57,652:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.79s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:09:57,849:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.17s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:09:58,403:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.05s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:09:58,753:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.80s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:09:59,118:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.87s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:10:00,370:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.25s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:10:03,062:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.78s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:10:05,791:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.93s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:10:10,070:INFO:Calculating mean and std
2023-09-10 16:10:10,071:INFO:Creating metrics dataframe
2023-09-10 16:10:10,779:INFO:Uploading results into container
2023-09-10 16:10:10,780:INFO:Uploading model into container now
2023-09-10 16:10:10,780:INFO:_master_model_container: 7
2023-09-10 16:10:10,781:INFO:_display_container: 2
2023-09-10 16:10:10,781:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=3846, verbose=0, warm_start=False)
2023-09-10 16:10:10,781:INFO:create_model() successfully completed......................................
2023-09-10 16:10:10,988:INFO:SubProcess create_model() end ==================================
2023-09-10 16:10:10,988:INFO:Creating metrics dataframe
2023-09-10 16:10:11,025:INFO:Initializing Quadratic Discriminant Analysis
2023-09-10 16:10:11,025:INFO:Total runtime is 2.912912464141846 minutes
2023-09-10 16:10:11,025:INFO:SubProcess create_model() called ==================================
2023-09-10 16:10:11,025:INFO:Initializing create_model()
2023-09-10 16:10:11,025:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:10:11,031:INFO:Checking exceptions
2023-09-10 16:10:11,031:INFO:Importing libraries
2023-09-10 16:10:11,031:INFO:Copying training dataset
2023-09-10 16:10:11,067:INFO:Defining folds
2023-09-10 16:10:11,067:INFO:Declaring metric variables
2023-09-10 16:10:11,072:INFO:Importing untrained model
2023-09-10 16:10:11,073:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-10 16:10:11,084:INFO:Starting cross validation
2023-09-10 16:10:11,087:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:10:12,241:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,303:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,406:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,437:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,591:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,668:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,753:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:12,802:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:15,734:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:15,753:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-09-10 16:10:20,127:INFO:Calculating mean and std
2023-09-10 16:10:20,127:INFO:Creating metrics dataframe
2023-09-10 16:10:20,815:INFO:Uploading results into container
2023-09-10 16:10:20,815:INFO:Uploading model into container now
2023-09-10 16:10:20,815:INFO:_master_model_container: 8
2023-09-10 16:10:20,815:INFO:_display_container: 2
2023-09-10 16:10:20,815:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-10 16:10:20,815:INFO:create_model() successfully completed......................................
2023-09-10 16:10:21,027:INFO:SubProcess create_model() end ==================================
2023-09-10 16:10:21,027:INFO:Creating metrics dataframe
2023-09-10 16:10:21,046:INFO:Initializing Ada Boost Classifier
2023-09-10 16:10:21,046:INFO:Total runtime is 3.0799370765686036 minutes
2023-09-10 16:10:21,046:INFO:SubProcess create_model() called ==================================
2023-09-10 16:10:21,058:INFO:Initializing create_model()
2023-09-10 16:10:21,058:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:10:21,058:INFO:Checking exceptions
2023-09-10 16:10:21,058:INFO:Importing libraries
2023-09-10 16:10:21,058:INFO:Copying training dataset
2023-09-10 16:10:21,094:INFO:Defining folds
2023-09-10 16:10:21,096:INFO:Declaring metric variables
2023-09-10 16:10:21,100:INFO:Importing untrained model
2023-09-10 16:10:21,104:INFO:Ada Boost Classifier Imported successfully
2023-09-10 16:10:21,115:INFO:Starting cross validation
2023-09-10 16:10:21,119:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:10:39,610:INFO:Calculating mean and std
2023-09-10 16:10:39,611:INFO:Creating metrics dataframe
2023-09-10 16:10:40,345:INFO:Uploading results into container
2023-09-10 16:10:40,345:INFO:Uploading model into container now
2023-09-10 16:10:40,345:INFO:_master_model_container: 9
2023-09-10 16:10:40,345:INFO:_display_container: 2
2023-09-10 16:10:40,345:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=3846)
2023-09-10 16:10:40,345:INFO:create_model() successfully completed......................................
2023-09-10 16:10:40,544:INFO:SubProcess create_model() end ==================================
2023-09-10 16:10:40,544:INFO:Creating metrics dataframe
2023-09-10 16:10:40,585:INFO:Initializing Gradient Boosting Classifier
2023-09-10 16:10:40,585:INFO:Total runtime is 3.405581351121267 minutes
2023-09-10 16:10:40,585:INFO:SubProcess create_model() called ==================================
2023-09-10 16:10:40,585:INFO:Initializing create_model()
2023-09-10 16:10:40,585:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:10:40,585:INFO:Checking exceptions
2023-09-10 16:10:40,585:INFO:Importing libraries
2023-09-10 16:10:40,590:INFO:Copying training dataset
2023-09-10 16:10:40,620:INFO:Defining folds
2023-09-10 16:10:40,620:INFO:Declaring metric variables
2023-09-10 16:10:40,627:INFO:Importing untrained model
2023-09-10 16:10:40,632:INFO:Gradient Boosting Classifier Imported successfully
2023-09-10 16:10:40,644:INFO:Starting cross validation
2023-09-10 16:10:40,647:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:11:24,566:INFO:Calculating mean and std
2023-09-10 16:11:24,572:INFO:Creating metrics dataframe
2023-09-10 16:11:25,449:INFO:Uploading results into container
2023-09-10 16:11:25,449:INFO:Uploading model into container now
2023-09-10 16:11:25,449:INFO:_master_model_container: 10
2023-09-10 16:11:25,449:INFO:_display_container: 2
2023-09-10 16:11:25,449:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=3846, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-10 16:11:25,449:INFO:create_model() successfully completed......................................
2023-09-10 16:11:25,668:INFO:SubProcess create_model() end ==================================
2023-09-10 16:11:25,668:INFO:Creating metrics dataframe
2023-09-10 16:11:25,689:INFO:Initializing Linear Discriminant Analysis
2023-09-10 16:11:25,689:INFO:Total runtime is 4.157315297921499 minutes
2023-09-10 16:11:25,694:INFO:SubProcess create_model() called ==================================
2023-09-10 16:11:25,694:INFO:Initializing create_model()
2023-09-10 16:11:25,694:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:11:25,694:INFO:Checking exceptions
2023-09-10 16:11:25,694:INFO:Importing libraries
2023-09-10 16:11:25,694:INFO:Copying training dataset
2023-09-10 16:11:25,727:INFO:Defining folds
2023-09-10 16:11:25,727:INFO:Declaring metric variables
2023-09-10 16:11:25,733:INFO:Importing untrained model
2023-09-10 16:11:25,738:INFO:Linear Discriminant Analysis Imported successfully
2023-09-10 16:11:25,751:INFO:Starting cross validation
2023-09-10 16:11:25,751:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:11:35,141:INFO:Calculating mean and std
2023-09-10 16:11:35,142:INFO:Creating metrics dataframe
2023-09-10 16:11:35,840:INFO:Uploading results into container
2023-09-10 16:11:35,840:INFO:Uploading model into container now
2023-09-10 16:11:35,842:INFO:_master_model_container: 11
2023-09-10 16:11:35,842:INFO:_display_container: 2
2023-09-10 16:11:35,842:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-10 16:11:35,842:INFO:create_model() successfully completed......................................
2023-09-10 16:11:36,038:INFO:SubProcess create_model() end ==================================
2023-09-10 16:11:36,038:INFO:Creating metrics dataframe
2023-09-10 16:11:36,068:INFO:Initializing Extra Trees Classifier
2023-09-10 16:11:36,069:INFO:Total runtime is 4.330323628584544 minutes
2023-09-10 16:11:36,075:INFO:SubProcess create_model() called ==================================
2023-09-10 16:11:36,075:INFO:Initializing create_model()
2023-09-10 16:11:36,075:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:11:36,075:INFO:Checking exceptions
2023-09-10 16:11:36,075:INFO:Importing libraries
2023-09-10 16:11:36,075:INFO:Copying training dataset
2023-09-10 16:11:36,130:INFO:Defining folds
2023-09-10 16:11:36,130:INFO:Declaring metric variables
2023-09-10 16:11:36,138:INFO:Importing untrained model
2023-09-10 16:11:36,139:INFO:Extra Trees Classifier Imported successfully
2023-09-10 16:11:36,156:INFO:Starting cross validation
2023-09-10 16:11:36,160:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:12:21,825:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.98s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:24,748:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 1.98s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:24,894:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.85s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:25,373:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.57s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:25,373:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.55s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:25,407:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:260: UserWarning: Persisting input arguments took 0.56s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  fitted_estimator = self._memory_fit(

2023-09-10 16:12:26,023:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.54s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:26,238:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.69s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:26,774:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.91s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:26,787:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.91s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:26,788:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.80s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:27,121:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.10s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:36,111:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.68s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-09-10 16:12:40,076:INFO:Calculating mean and std
2023-09-10 16:12:40,110:INFO:Creating metrics dataframe
2023-09-10 16:12:40,843:INFO:Uploading results into container
2023-09-10 16:12:40,852:INFO:Uploading model into container now
2023-09-10 16:12:40,856:INFO:_master_model_container: 12
2023-09-10 16:12:40,856:INFO:_display_container: 2
2023-09-10 16:12:40,858:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=3846, verbose=0, warm_start=False)
2023-09-10 16:12:40,858:INFO:create_model() successfully completed......................................
2023-09-10 16:12:41,569:INFO:SubProcess create_model() end ==================================
2023-09-10 16:12:41,569:INFO:Creating metrics dataframe
2023-09-10 16:12:41,598:INFO:Initializing Light Gradient Boosting Machine
2023-09-10 16:12:41,598:INFO:Total runtime is 5.422473315397899 minutes
2023-09-10 16:12:41,602:INFO:SubProcess create_model() called ==================================
2023-09-10 16:12:41,602:INFO:Initializing create_model()
2023-09-10 16:12:41,602:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:12:41,602:INFO:Checking exceptions
2023-09-10 16:12:41,603:INFO:Importing libraries
2023-09-10 16:12:41,603:INFO:Copying training dataset
2023-09-10 16:12:41,662:INFO:Defining folds
2023-09-10 16:12:41,663:INFO:Declaring metric variables
2023-09-10 16:12:41,666:INFO:Importing untrained model
2023-09-10 16:12:41,671:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-10 16:12:41,683:INFO:Starting cross validation
2023-09-10 16:12:41,685:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:12:55,158:INFO:Calculating mean and std
2023-09-10 16:12:55,160:INFO:Creating metrics dataframe
2023-09-10 16:12:55,777:INFO:Uploading results into container
2023-09-10 16:12:55,777:INFO:Uploading model into container now
2023-09-10 16:12:55,777:INFO:_master_model_container: 13
2023-09-10 16:12:55,777:INFO:_display_container: 2
2023-09-10 16:12:55,777:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=3846, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-10 16:12:55,777:INFO:create_model() successfully completed......................................
2023-09-10 16:12:55,976:INFO:SubProcess create_model() end ==================================
2023-09-10 16:12:55,976:INFO:Creating metrics dataframe
2023-09-10 16:12:56,010:INFO:Initializing Dummy Classifier
2023-09-10 16:12:56,010:INFO:Total runtime is 5.662673131624858 minutes
2023-09-10 16:12:56,012:INFO:SubProcess create_model() called ==================================
2023-09-10 16:12:56,016:INFO:Initializing create_model()
2023-09-10 16:12:56,016:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026B250D91F0>, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:12:56,016:INFO:Checking exceptions
2023-09-10 16:12:56,016:INFO:Importing libraries
2023-09-10 16:12:56,016:INFO:Copying training dataset
2023-09-10 16:12:56,055:INFO:Defining folds
2023-09-10 16:12:56,056:INFO:Declaring metric variables
2023-09-10 16:12:56,063:INFO:Importing untrained model
2023-09-10 16:12:56,068:INFO:Dummy Classifier Imported successfully
2023-09-10 16:12:56,075:INFO:Starting cross validation
2023-09-10 16:12:56,079:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-10 16:12:57,511:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,547:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,611:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,680:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,742:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,763:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,779:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:57,827:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:59,825:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:12:59,988:WARNING:c:\Users\LP00035\anaconda3\envs\mlflow\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-09-10 16:13:03,700:INFO:Calculating mean and std
2023-09-10 16:13:03,702:INFO:Creating metrics dataframe
2023-09-10 16:13:04,304:INFO:Uploading results into container
2023-09-10 16:13:04,304:INFO:Uploading model into container now
2023-09-10 16:13:04,304:INFO:_master_model_container: 14
2023-09-10 16:13:04,304:INFO:_display_container: 2
2023-09-10 16:13:04,304:INFO:DummyClassifier(constant=None, random_state=3846, strategy='prior')
2023-09-10 16:13:04,304:INFO:create_model() successfully completed......................................
2023-09-10 16:13:04,526:INFO:SubProcess create_model() end ==================================
2023-09-10 16:13:04,526:INFO:Creating metrics dataframe
2023-09-10 16:13:04,570:INFO:Initializing create_model()
2023-09-10 16:13:04,570:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026B2519DC70>, estimator=LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=3846, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-09-10 16:13:04,570:INFO:Checking exceptions
2023-09-10 16:13:04,574:INFO:Importing libraries
2023-09-10 16:13:04,574:INFO:Copying training dataset
2023-09-10 16:13:04,610:INFO:Defining folds
2023-09-10 16:13:04,610:INFO:Declaring metric variables
2023-09-10 16:13:04,610:INFO:Importing untrained model
2023-09-10 16:13:04,610:INFO:Declaring custom model
2023-09-10 16:13:04,610:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-10 16:13:04,610:INFO:Cross validation set to False
2023-09-10 16:13:04,610:INFO:Fitting Model
2023-09-10 16:13:05,900:INFO:[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
2023-09-10 16:13:05,900:INFO:[LightGBM] [Info] Number of positive: 25647, number of negative: 78422
2023-09-10 16:13:05,916:INFO:[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003191 seconds.
2023-09-10 16:13:05,916:INFO:You can set `force_row_wise=true` to remove the overhead.
2023-09-10 16:13:05,916:INFO:And if memory is not enough, you can set `force_col_wise=true`.
2023-09-10 16:13:05,916:INFO:[LightGBM] [Info] Total Bins 281
2023-09-10 16:13:05,916:INFO:[LightGBM] [Info] Number of data points in the train set: 104069, number of used features: 16
2023-09-10 16:13:05,916:INFO:[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.246442 -> initscore=-1.117678
2023-09-10 16:13:05,916:INFO:[LightGBM] [Info] Start training from score -1.117678
2023-09-10 16:13:06,707:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=3846, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-10 16:13:06,707:INFO:create_model() successfully completed......................................
2023-09-10 16:13:06,975:INFO:_master_model_container: 14
2023-09-10 16:13:06,975:INFO:_display_container: 2
2023-09-10 16:13:06,978:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=3846, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-10 16:13:06,978:INFO:compare_models() successfully completed......................................
